apiVersion : apps/v1
kind: Deployment
metadata:
  name: "petestaks-1957"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "petestaks-1957"
  template:
    metadata:
      labels:
        app: "petestaks-1957"
    spec:
      containers:
        - name: "petestaks-1957"
          image: "aadapptestacr.azurecr.io/petestaks"
          ports:
          - containerPort: 8123