apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akstest-3057"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akstest-3057"
  template:
    metadata:
      labels:
        app: "akstest-3057"
    spec:
      containers:
        - name: "akstest-3057"
          image: "aaaatiwarishubregistry.azurecr.io/akstest"
          ports:
          - containerPort: 8123