apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ajayaks12321-abd3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ajayaks12321-abd3"
  template:
    metadata:
      labels:
        app: "ajayaks12321-abd3"
    spec:
      containers:
        - name: "ajayaks12321-abd3"
          image: "petestsu1.azurecr.io/ajayaks12321"
          ports:
          - containerPort: 8123