apiVersion: v1
kind: Service
metadata:
    name: "akstest-3057"
    labels:
        app: "akstest-3057"
spec:
    type: LoadBalancer
    ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
    selector:
        app: "akstest-3057"