on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testreg.azurecr.io
        username: ${{ secrets.acr_testreg_username }}
        password: ${{ secrets.acr_testreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t testreg.azurecr.io/kubernete:${{ github.sha }} --label dockerfile-path=aspnet-core-dotnet-core/Dockerfile
        docker push testreg.azurecr.io/kubernete:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernete_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: testreg.azurecr.io
        container-registry-username: ${{ secrets.acr_testreg_username }}
        container-registry-password: ${{ secrets.acr_testreg_password }}
        secret-name: kubernetedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          testreg.azurecr.io/kubernete:${{ github.sha }}
        imagepullsecrets: |
          kubernetedockerauth
