on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n kubernestusregistry -g kubernestusregistry82c4-rg --location "South Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n kubernestusregistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n kubernestusregistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n kubernestusregistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: kubernestusregistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t kubernestusregistry.azurecr.io/kubernete:${{ github.sha }} --label dockerfile-path=aspnet-core-dotnet-core/Dockerfile
        docker push kubernestusregistry.azurecr.io/kubernete:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kubernete_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernete9d85 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernete9d85`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernete9d85
        container-registry-url: kubernestusregistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kubernetedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubernete9d85
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          kubernestusregistry.azurecr.io/kubernete:${{ github.sha }}
        imagepullsecrets: |
          kubernetedockerauth   
