on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aadapptestacr.azurecr.io
        username: ${{ secrets.acr_aadapptestacr_username }}
        password: ${{ secrets.acr_aadapptestacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t aadapptestacr.azurecr.io/kubernete:${{ github.sha }} --label dockerfile-path=aspnet-core-dotnet-core/Dockerfile
        docker push aadapptestacr.azurecr.io/kubernete:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernete_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kuberneteb7be | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kuberneteb7be`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kuberneteb7be
        container-registry-url: aadapptestacr.azurecr.io
        container-registry-username: ${{ secrets.acr_aadapptestacr_username }}
        container-registry-password: ${{ secrets.acr_aadapptestacr_password }}
        secret-name: kubernetedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kuberneteb7be
        manifests: |
          manifests/deployment-14.yml
          manifests/service-14.yml
        images: |
          aadapptestacr.azurecr.io/kubernete:${{ github.sha }}
        imagepullsecrets: |
          kubernetedockerauth
