on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 1233newprod.azurecr.io
        username: ${{ secrets.acr_1233newprod_username }}
        password: ${{ secrets.acr_1233newprod_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t 1233newprod.azurecr.io/ajayaks12321:${{ github.sha }} --label dockerfile-path=aspnet-core-dotnet-core/Dockerfile
        docker push 1233newprod.azurecr.io/ajayaks12321:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ajayaks12321_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ajayaks123218a9a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ajayaks123218a9a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ajayaks123218a9a
        container-registry-url: 1233newprod.azurecr.io
        container-registry-username: ${{ secrets.acr_1233newprod_username }}
        container-registry-password: ${{ secrets.acr_1233newprod_password }}
        secret-name: ajayaks12321dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ajayaks123218a9a
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          1233newprod.azurecr.io/ajayaks12321:${{ github.sha }}
        imagepullsecrets: |
          ajayaks12321dockerauth
